### PR TITLE
Fixing some issues discovered when migrating my-account

### PR DESCRIPTION
**Pull request by shahata**

### CODE REVIEW

**Comment by shahata** [comment]
@donataswix can u plz create a new release with this change?

**Comment by shahata** [comment]
wat. it seems you already did? how?

**Comment by donataswix** [comment]
There are no releases, I've simply merged this to master. You must be using master branch as dependency. Do you still want me to do a version release, like 1.0.0?

**Comment by shahata** [comment]
oh, I see. any reason not to pubish this to npm?

**Comment by donataswix** [comment]
None in particular. Should we?

**Pull request merged**
